### ISSUE TITLE
Extension changes size of context menu

### ISSUE THREAD

**Issue by mvrck19** [dracula/firefox#1]
The extension changes the size of the Firefox context menu causing me this bug : https://support.mozilla.org/en-US/questions/1180792
I fixed it by changing to another theme.

**Comment by RaphGL** [comment]
This seems to have been a bug caused by previous versions of Firefox. I haven't experienced it since about Firefox 77 I think. I'd suggest you to give it a try again and report back.

**Comment by mvrck19** [comment]
Yeah, I think its fine now
