### ISSUE TITLE
Open Pull-Requests on Github have a red background, which is confusing on first glance

### ISSUE THREAD

**Issue by marcel-wollschlaeger** [dracula/firefox#6]
When you browse Github for Issues or Pull-Requests, they currently look like this:

- Issues: 
![Screenshot 2023-02-17 at 13 05 12](https://user-images.githubusercontent.com/122972055/219649465-b13dcf40-f28c-44c0-b47c-0993d0092b36.png)
- PR overview:
![Screenshot 2023-02-17 at 13 03 23](https://user-images.githubusercontent.com/122972055/219649479-63f1bdd3-64c5-4193-bca1-f4c3d285f182.png)
- Detailed PR:
![Screenshot 2023-02-17 at 13 03 29](https://user-images.githubusercontent.com/122972055/219649488-1ebbf7ac-8be2-41d7-b013-18cc1c8ed26d.png)

I don't know really if this can be changed, but I'd love to see them more like this:
<img width="1296" alt="Screenshot 2023-02-17 at 13 07 32" src="https://user-images.githubusercontent.com/122972055/219649850-bbcd128d-cc86-4a6d-90e2-fe623d15d74a.png">

**Comment by RaphGL** [comment]
Hey, I'm only a maintainer for this repo. I do not have any control over that stuff. Consider creating an issue on https://github.com/dracula/dracula-theme
