### ISSUE TITLE
Active tab has a white border in Firefox Nightly

### ISSUE THREAD

**Issue by MeatyChunks** [dracula/firefox#9]
Hope this is the right place to put this - 
![image](https://github.com/dracula/firefox/assets/6160351/935d9d44-27a5-4fa5-875f-3d5cceb810a8)

I narrowed it down to this change using mozregression if it helps: https://phabricator.services.mozilla.com/D196159

Cheers!

**Comment by RaphGL** [comment]
Thanks for reporting, I'll look into it tomorrow. I don't really use Nightly but I'll try installing it and giving it a shot and fixing it

**Comment by ovilaro** [comment]
I can confirm that it happens in Firefox Developer Edition (I think it is on par with the current Beta):

<img width="742" alt="imatge" src="https://github.com/dracula/firefox/assets/861367/c05ba6aa-b190-44d5-8942-3e7fef50f63b">

**Comment by RaphGL** [comment]
Tried changing it but failed to do so on nightly. Looking at that diff the class itself got changed to something that's transparent but the field itself did not change. I'm not sure what is causing the breakage. If someone manages to fix it I'd appreciate it. I'll try digging in later to see if I can find a fix as well.

If not I'll have to wait until this change comes to stable and there's (hopefully) documentation on what changed.

**Comment by MeatyChunks** [comment]
I finally had a little look into this and it seems adding a `tab_line` field fixes things. I used `"tab_line": "rgb(68, 71, 90)",`, I'm just not sure if it's 100% the right colour or not!

**Comment by RaphGL** [comment]
@MeatyChunks yeah that seems to be the same color as `tab_selected`. Seems right by me. Would you like to make a PR or should I make the change myself?

**Comment by MeatyChunks** [comment]
You're welcome to do it, that would be much appreciated thank you. 😃
